version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  nginx:
    image: docker.arvancloud.ir/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app


#  apache:
#    image: docker.arvancloud.ir/httpd:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
#    depends_on:
#      - app